Revert "vboot: Enable diagnostics on Dirinboz"
This reverts commit 442c0b23870ce799140ac962ac2a24dfada81df6.

Reason for revert: 2kernel.c doesn't build:
firmware/2lib/2kernel.c:137:7: error: implicit declaration of function 'strncasecmp'; did you mean 'strncmp'? [-Werror=implicit-function-declaration]



Original change's description:
> vboot: Enable diagnostics on Dirinboz
>
> Enable diagnostics on Dirinboz only.
> This CL should not be merged to ToT.
>
> BRANCH=zork
> BUG=b:170789297
> TEST=none
>
> Cq-Depend: chromium:2484207
> Signed-off-by: Hsuan Ting Chen <roccochen@chromium.org>
> Change-Id: Iacdfbe292b721e430cd5bbc53b435611d0f7a0d0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/2484206
> Tested-by: Martin Roth <martinroth@google.com>
> Reviewed-by: Hung-Te Lin <hungte@chromium.org>
> Reviewed-by: Martin Roth <martinroth@google.com>
> Commit-Queue: Martin Roth <martinroth@google.com>

Bug: b:170789297
Change-Id: Ibe5f33225de6a79dfa2ac2e188db0f26d0d39caa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/2495865
Reviewed-by: Martin Roth <martinroth@google.com>
Commit-Queue: Martin Roth <martinroth@google.com>
Tested-by: Martin Roth <martinroth@google.com>
Auto-Submit: Martin Roth <martinroth@google.com>