futility: Fix -Wstrict-prototypes warning
ToT clang is complaining about missing 'void' in
function prototype.
futility/updater.c:1235:42:
error: a function declaration without a prototype is
deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct updater_config *updater_new_config()
                                          ^
                                          void
BUG=b:230345382
TEST=CQ, llvm tot test
BRANCH=none

Signed-off-by: Manoj Gupta <manojgupta@google.com>
Change-Id: Ic68b71a7413e9396904dd319e0febce2eecb0df3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/3610725
Reviewed-by: Julius Werner <jwerner@chromium.org>
Commit-Queue: Julius Werner <jwerner@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Auto-Submit: Manoj Gupta <manojgupta@chromium.org>