fuzzers: Fix builds with new clang
Clang is complaining about missing prototypes e.g.
tests/vb2_preamble_fuzzer.c:43:13: error: no previous
prototype for function 'vb2_check_padding'
[-Werror,-Wmissing-prototypes]

Add the header "2rsa_private.h" to fix fuzzer builders.

BUG=chromium:1172055
TEST=tryjob

Signed-off-by: Manoj Gupta <manojgupta@google.com>
Change-Id: I9593e1f747939a38c33226f98570fa5423570362
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/2658033
Reviewed-by: Julius Werner <jwerner@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Auto-Submit: Manoj Gupta <manojgupta@chromium.org>